baseurl: ""
url: "https://scrlkx.github.io"

author: "Daniel Freitas"
nickname: "@scrlkx"
email: ["me@scrlkx.com", "work@scrlkx.com"]
social:
  github: "https://github.com/scrlkx"
  gitlab: "https://gitlab.com/scrlkx"

plugins:
  - jekyll-postcss

postcss:
  cache: false
